language: bash
matrix:
  include:
  - os: osx
    language: node_js
    node_js:
    - 12.4.0
    cache:
      npm: false
  - os: windows
    env:
    - YARN_GPG=no
    language: node_js
    node_js:
    - 12.4.0
    cache:
      npm: false
  - os: linux
    env: BASE_IMAGE=library/debian QEMU_ARCH=x86_64 DOCKERFILE="Dockerfile.debian"
    node_js:
    - 12.4.0
    services:
    - docker
before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get --yes --no-install-recommends
  install binfmt-support qemu-user-static ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm --privileged multiarch/qemu-user-static:register
  --reset ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install -g prebuild ; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm install -g prebuild ; fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f .prebuild/$DOCKERFILE
  --build-arg BASE_IMAGE=${BASE_IMAGE} --build-arg QEMU_ARCH=${QEMU_ARCH} -t multiarch-build
  . ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run --rm -v $(pwd):/node-pty
  multiarch-build ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then prebuild -t 12.4.0 -t 10.16.3 ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then prebuild -t 6.0.10 -r electron ; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then prebuild -t 12.4.0 -t 10.16.3 --include-regex
  "\.(node|exe|dll|pdb)$" ; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then prebuild -t 6.0.10 -r electron --include-regex
  "\.(node|exe|dll|pdb)$" ; fi
deploy:
  provider: releases
  api_key:
    secure: RM7U+MLzQ1Ck81jmXGWwdoK4P+zgyhzSGOag3+41inKotnwJiWpPM7DzgFTBGaEy3eXngyA8mB7mxjtAZIU6l7Bderj4F1bgSQ2ZZfeVNt66K19RFl6n448BHL2ZWXPMH/5Z6Y0aEBsIFAQRPFwVHuSQUAnar8O1P4trzPIoP5ZR70chA3j+v3frdaR5G1JF1APoeWmUNhIsDwaZTpnCfOTRbahsE2xI7jbVHsstXFR0JT1j3WwI5h1M380nCM+UhZGROOliDvBr1Sc7LCKRzCeNa+M2x6vipyE1NXU0m3Zo5+v9JAyV66F+Pk8pQCB6Q6+4g68J/FMU281soaHYp7eY7vIHBq0wa99OD+/q4ROBo/Uwo1DZQN42quBdG1hCLL6XPIVBt9uQQ92Z3Y83yU35DnrOkLi6r2uv9At9hzjRqROKgM4o8vT049iQj8kMpzT1/xb0oYWWLAJeBRJSIqI5KNd7q8o5YRnnmVqmDsSUcNErbCV5s1UP+dwtUUZzlqnrllSNSQLRdSuwE48FF68rrC3gVga8NCUc+14ayauG195XD7EGe1rKDRZcu5ZVs6I6/MPpWZRCFAgtoMk6yniRxrKR1b2yF02rJ1+WNXvFPozkZ/i5vwCpHRCFqUxENH6BGXpDXGiv1TQ+4Fl7o7jd0TJ/J9ekvlluOxTIK3c=
  file_glob: true
  file: prebuilds/*.tar.gz
  skip_cleanup: true
  on:
    repo: alexxed/node-pty
    tags: true
